# Generated by Django 5.2.1 on 2025-09-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DishApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='poster',
            field=models.ImageField(upload_to='posters/'),
        ),
    ]
